runner:
  textlint:
    cmd: npx textlint -f compact doc/*.md
    errorformat:
      - "%f:%l:%c: %m"
      - "%f: line %l, col %c, %m"
  redpen-doc:
    cmd: redpen -c config/redpen-conf-ja.xml -L ja -l 9999 -r plain doc/*.md
    errorformat:
      - "doc/%f:%l: %m"
