runner:
  textlint:
    cmd: npx textlint -f compact doc/*.md
    errorformat:
      - "%f:%l:%c: %m"
      - "%f: line %l, col %c, %m"
  redpen:
    cmd: redpen -c config/redpen-conf-ja.xml -f markdown -l 0 -r plain doc/*.md
    errorformat:
      - "%f:%l: %m"
